name: PHP tests
on: [push, pull_request]
jobs:
  php-linter:
    name: PHP Syntax check 5.6|7.2|7.3|8.0|8.1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: PHP syntax checker 5.6
        uses: prestashop/github-action-php-lint/5.6@master

      - name: PHP syntax checker 7.2
        uses: prestashop/github-action-php-lint/7.2@master

      - name: PHP syntax checker 8.0
        uses: prestashop/github-action-php-lint/8.0@master

      - name: PHP syntax checker 8.1
        uses: prestashop/github-action-php-lint/8.1@master

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache vendor folder
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Cache composer folder
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: php-composer-cache

      - run: composer install

      - run: composer install
        working-directory: tests/Symfony3

      - run: composer install
        working-directory: tests/Symfony4

      - name : Run PHPStan for Symfony 3
        run: composer run phpstan-sf3

      - name : Run PHPStan for Symfony 4
        run: composer run phpstan-sf4

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache vendor folder
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Cache composer folder
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: php-composer-cache

      - run: composer install

      - name: Run PHPUnit
        run: vendor/bin/phpunit tests/Unit
